version: '3'
services:
  localai:
    image: localai/localai:v2.11.0-aio-cpu
    container_name: ${APP_NAME}-localai
    # For Nvidia GPUs decomment one of the following (cuda11 or cuda12):
    # image: localai/localai:v2.11.0-aio-gpu-cuda-11
    # image: localai/localai:v2.11.0-aio-gpu-cuda-12
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/readyz"]
      interval: 1m
      timeout: 20m
      retries: 5
    ports:
      - 8080:8080
    environment:
      - DEBUG=true
      # ...
    volumes:
      - ./models:/build/models:cached
    # decomment the following piece if running with Nvidia GPUs
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
  app:
    image: node:20-alpine
    container_name: ${APP_NAME}-app
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=${NODE_ENV}
    user: "node"
    command: npm start
